services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin-image-jelly
    restart: unless-stopped
    user: "0:0"
    environment:
      TZ: Europe/Paris
    ports:
      - "8101:8096"

    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./jellyfin-config:/config
      - ./jellyfin-cache:/cache
      - type: bind
        source: /mnt/decypharr-poc
        target: /data
        read_only: true
        bind:
          propagation: rshared
      - /mnt/ATHENA:/ATHENA:ro
      - /mnt/NEMESIS:/NEMESIS:ro
    labels:
      io.portainer.accesscontrol.users: appboximage-jelly
      marinos.appbox.id: image-jelly
      marinos.appbox.type: jellyfin
      marinos.appbox.node: orion

networks:
  default:
    name: appbox-shared
    external: true
